### ISSUE TITLE
[question] - SharedArrayBuffer is not available

### ISSUE THREAD

**Issue by Sparkenstein** [kleisauke/wasm-vips#18]
Need to simply know if wasm-vips will work without SharedArrayBuffer with some efforts?

Background:
I am working on a desktop application. as it's a desktop application, there's no 'server' per se. so I can't really set the headers to make SharedArrayBuffer available easily. I have been digging into other alternatives to make this work but it's been a long time and I haven't found anything substantial.

Is there any way I will be able to make wasm-vips work without SAB api? I am fine with performance hit. or any other vips lib that you are aware of that doesn't use SAB api? any help is appreciated I have been chasing this for a long time

**Comment by kleisauke** [comment]
The [SharedArrayBuffer API](https://caniuse.com/sharedarraybuffer), as required by [Emscripten pthreads integration](https://emscripten.org/docs/porting/pthreads.html), is currently a hard-requirement. There's no workaround for this since libvips requires threading functionality to be available.

Hopefully this will no longer be an issue when WebAssembly standardizes its https://github.com/WebAssembly/stack-switching proposal and Emscripten adopts that for their pthreads integration.

**Comment by kleisauke** [comment]
Note that you could use https://github.com/gzuidhof/coi-serviceworker for situations where you can't modify the headers (e.g. GitHub pages).

**Comment by Sparkenstein** [comment]
Thanks for the pointers
I have tried coi-serviceworker. but I got the same problem rest of of users are getting -- page keeps refreshing again and again forever. I believe that's because crossOriginIsolated is never true? 

Check out this.
https://github.com/gzuidhof/coi-serviceworker/issues/5

But anyway thanks for your time, if it's something required by emscripten we can't really do anything. at the moment my last resort is writing some bindings in rust and use that. might be faster than waiting for webassembly proposal.

**Comment by kleisauke** [comment]
FWIW, according to https://stackoverflow.com/questions/68609682/is-there-any-way-to-use-sharedarraybuffer-on-github-pages/68675301#comment129294263_68675301 that can happen when `coi-serviceworker.js` was not served from the top-level directory.
