### ISSUE TITLE
Usage on Cloudflare Worker

### ISSUE THREAD

**Issue by chocolatkey** [kleisauke/wasm-vips#2]
Hello,

This is a cool project, and I was thinking of using it in Cloudflare Workers and saw your card here https://github.com/kleisauke/wasm-vips/projects/1#card-44661973
There's a hurdle, however, that prevents this from being possible: "The module and script together must be under 1MB after gzip compression" - https://community.cloudflare.com/t/what-is-the-maximum-allowed-size-of-a-webassembly-module/66453/2

The .wasm file is ~4.3 MB uncompressed, and ~1.41MB (gzip 9) compressed. Maybe a slimmed version of the library could still be used, with some support for formats dropped?

**Comment by wis** [comment]
execution time is an issue too, you would easily hit the 50 millisecond CPU execution time limit (Workers Bundled plan, free-tier is 10ms) for trivial tasks/operations.

judging by the [Speed and memory use](https://github.com/libvips/libvips/wiki/Speed-and-memory-use) from libvips' Wiki, memory consumption is not an issue for using libvips in Workers unlike alternative/competing libraries (33MB is under the 128MB memory limit), however 520ms/(50ms+) CPU execution time is (if you can't use [Workers Unbound](https://blog.cloudflare.com/introducing-workers-unbound/)):
![speed2-fs8](https://user-images.githubusercontent.com/9993663/95597086-e166ad80-0a56-11eb-8424-9af7a4f15e3e.png)

**Comment by YamiteruXYZ** [comment]
Workers unbound is still pretty cheap so no problem with that. I think it has a lot of potential.

**Comment by kleisauke** [comment]
I still need to investigate whether this project can be supported on Cloudflare Workers, but note that this is being done on best effort. `vips.wasm` is now around 3.98 MB on the [`vips-8.11`](https://github.com/kleisauke/wasm-vips/tree/vips-8.11) branch with `-O3`. A possible way to slim down the WebAssembly output is to compile it with `-Oz` instead of `-O3`.
https://github.com/kleisauke/wasm-vips/blob/128e6782da21500c344d4b754854627d89560aee/build.sh#L67
https://github.com/kleisauke/wasm-vips/blob/128e6782da21500c344d4b754854627d89560aee/build.sh#L72

And to disable unnecessary loaders/savers via libvips' configure flags:
https://github.com/kleisauke/wasm-vips/blob/128e6782da21500c344d4b754854627d89560aee/build.sh#L310-L312

That said, it seems that Cloudflare maintains a ["no background threads" policy](
https://community.cloudflare.com/t/fixed-cloudflare-workers-slow-with-moderate-sized-webassembly-bindings/184668/12) because of the potential for Spectre attacks, which could cause problems with wasm-vips as it requires the [SharedArrayBuffer API](https://caniuse.com/sharedarraybuffer) to be available (for V8, an additional argument, `--experimental-wasm-threads`, must be specified for this). AFAIK, there's no workaround for this since libvips requires threading functionality to be available.

**Comment by smashah** [comment]
Please sign up to Larger script sizes for CFW here:

https://www.cloudflare.com/larger-scripts-on-workers-early-access/

**Comment by sixers** [comment]
Hey, is there any update on this issue?

**Comment by kleisauke** [comment]
> Hey, is there any update on this issue?

@sixers No updates, comment https://github.com/kleisauke/wasm-vips/issues/2#issuecomment-1187416552 is still relevant at the time of writing (and I do _not_ expect a resolution soon). Issue #18 might also be relevant here.

**Comment by kleisauke** [comment]
Cloudflare has updated its documentation to mention that neither threading nor the Web Workers API is supported:
https://developers.cloudflare.com/workers/platform/web-assembly/#threading

Given that libvips requires threading functionality to be available, I'll close this as "won't fix" for now.

**Comment by mojodevagentsix** [comment]
Hello @kleisauke, 
I've successfully implemented libvips with WebAssembly on Cloudflare Pages, which is performing excellently. I'm now looking to extend this implementation to Cloudflare Pages Functions to create an API endpoint with the same capabilities. As someone with extensive expertise in libvips, could you provide guidance on the best approach for this migration?"
As I have tried but getting failed to load the vips module error.

**Comment by kleisauke** [comment]
@mojodevagentsix Cloudflare Pages Functions uses the Cloudflare Workers runtime, which does not currently support threading nor the Web Workers API. If performance isn't of concern then perhaps try [jimp](https://www.npmjs.com/package/jimp).
