### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by JoxC** [kleisauke/wasm-vips#6]
Build with `npm run build` on Mac, I always got this:

> [ 80%] Linking CXX executable ../../../../lib/web/vips.js
> wasm-ld: error: unable to find library -lUSE_PTHREADS=1
> wasm-ld: error: unable to find library -lUSE_PTHREADS=1
> wasm-ld: error: unable to find library -lUSE_PTHREADS=1

**Comment by kleisauke** [comment]
As mentioned in https://github.com/kleisauke/wasm-vips/issues/4#issuecomment-883570352 it looks like a patch has not been applied during the build of the Docker image (perhaps due to a temporary network failure?). I could not reproduce this on Linux (and don't have access to a Mac). As a possible workaround for now, you can simulate that patch by using this `sed` replacement:
```bash
$ sed -i 's/-s USE_PTHREADS=1/-pthread/g' build/target/lib/pkgconfig/{gio,glib,gmodule-no-export,gobject}-2.0.pc
```

After that, the build should proceed without any problems. Note that if you want to rebuild all dependencies, you can just remove the `build/target` directory.

**Comment by JoxC** [comment]
@kleisauke `sed` command works. Thanks for your help!
