### ISSUE TITLE
Question: Javascript API documentation

### ISSUE THREAD

**Issue by boustanihani** [kleisauke/wasm-vips#72]
Hi, just wondering were to find the Javascript API documentation (functions & variables).

I would like to read all metadata (XMP, EXIF & IPTC) from a JPG image using a browser, maybe edit the metadata a little bit, and finally export a new JPG file containing all metadata.

Could you possible give an example to how this could be achieved?

**Comment by kleisauke** [comment]
Hi @boustanihani,

The API documentation is still on the roadmap.  In the meantime, the type definitions at [`lib/vips.d.ts`](https://github.com/kleisauke/wasm-vips/blob/master/lib/vips.d.ts) provide an overview of all functions and variables in wasm-vips. Additionally, the introduction to pyvips, which has a similar API to wasm-vips, can serve as a getting started guide:
https://libvips.github.io/pyvips/intro.html

> I would like to read all metadata (XMP, EXIF & IPTC) from a JPG image using a browser, maybe edit the metadata a little bit, and finally export a new JPG file containing all metadata.

I created an example demonstrating how to achieve this on [this playground link](https://wasm-vips.kleisauke.nl/playground/?deflate=dVNhT9swEP0rt2pSUtEmSEPAgPKhjE6V0JhoJyYRJNz4krpz7Mh2mpWq_31nN-vgw74k8fm9d8_vnKdemsKdZhyYAlGxEqEwugIGtUFJdeRQCImZItw07FvdmBwvYOlcbS_StG3bpJAi_2WSXFdpvdRO23TFrFaCv6LhLP30-fzs7Pzk5PQ0UxIdNYIRrEVtkyCZKGwn1HVCjeJItzJZ1WXUv8xUaPuVGAyksA50AUxKcEuECh3jzDGyh5Jb0CqUwxkylWtF8G5rRNWkRDcJy9gLF9pAHKzQ7vElva46dGLFKxIGjo5EH7aZAvBiWmIidRl3IFKLRd8r7TqXD1jptVBlypxj-ZK-DhYHoJBydJqU6s1bmyEIMufrwVeQmpGv25_TCXiyByUW3cwZ0owj_C2KoSj48TBk9wVtbkTthFbRAKJv2pC8UTBj7fBxSUL3rQxR_k9lpgvXMoPEfpFi4acCH7dhOGs0lnTj_u7l4C0cE2H6fX4T7A1A0EzUhhoUEO9znm9q1EUcka186EFRHz6MKOcuT0KZIPMO8ibLRyMchpwM2kY6Hx2DhdSLv5PVjRs3RYFmn1_rCXO9L8XR4f7swZ5IOLplMKbP-OnAfh7AFhzZvYAojCRd1VhGsHtP_vFwR3x6JrlB5vB-scLc0Tr2u_-woioJx3XeVKhcB76V6Fd01mpvit6JNTkhO22qHTgUX0cYb6ac_obG1Y2L-gmra1T8Zikkp5hLL9Qb9K64WIPgo6y3B2a966uUatdhlx7PfwA&modules=).

**Comment by boustanihani** [comment]
@kleisauke Thanks a lot for the information :)

**Comment by boustanihani** [comment]
@kleisauke thanks again for the nice example.

Could you possibly provide an example that prints out the `iptc-data` in a human readable form (like JSON for example), and then edit (modify/remove/add) some of the IPTC fields? Does `wasm-vips` support that type of operations?

```
...
const fields = im.getFields();
for (let i = 0; i < fields.size(); ++i) {
  console.log(fields.get(i));
}
console.log(im.getBlob('iptc-data'));
```

![Bildschirmfoto vom 2024-10-24 14-39-44](https://github.com/user-attachments/assets/2635c18d-3080-4a9e-aa14-4a0d92c98d8c)

**Comment by kleisauke** [comment]
You can read and write IPTC data in libvips, but you need to handle the parsing and serialization manually. See for example [this playground link](https://wasm-vips.kleisauke.nl/playground/?deflate=rVVpc9MwEP0rS7_EmTZOArRAS2HS0EKHq5OYYybpdBR77QhkySPJTc3x31nJdpKWDp-Yyfm0q3379vBsp9-Hac6EAFMuDFpQKSytLcxhv483PLVKiVDprB-x7APL0fTPL6JxuLS5mMtYSWMh5SiS96yAY_g5lwCDm8HZIXTGzGKmdNXZq8HhMwLfYrVSOjEt-OgJga_IcqyRPpMW3x8QflIJLnEN7a-hiFuxxg_cvW-QJdvGB6eOgcaE2xZ68thBqqg0z5Yb9KmnWliu5BobbbAvmlvUnbn8fTSXc5mWMnYwEN3EKUHcWZDQR7dOnuT8oCwegsQVfOLSPh1pzaqgC14sXcZWaYid4NyQESaYgFWNa-xVACahlGbJiD-5FZUril0i2KoghLkLQ-fh4pLqd0J5Np4t1EG93WdOVrWt4-z-estwUaYpaufQmlMAV8s64xacnl6MJqPo4-Rq_GY0oXOq6NgLBjCNRpPo6uPZVXT6NdqcDx42N6SUciCoubjDj-jruecUCpSZXR7B7i5v9APgKXhijmGYofWZBXT-4Pj4Lotfv2qfWoo7HrALw8brL37d1o-Ss1yW2DBtszWY5ShtRIIT5fsvf1hrVjN-EGy7cLmeiq6v_H0x3K1T_uO-AMMDH-FRG2Fr0NwQkkd7_Wwr7OXf1p-ZKJ25K3uEN_YVxipBHXTDxP-qW4BG3zeVD7q_R_WhL3q3DLttO9W5ku1szeVyXThwjbN1QGF9Q4bc1I15x6_1AngJszAMbx_vbSVwuTE9hNk_7BoBfgMKg__gtXFpPdr83Dr8zgtwU8-oahmoa9R--haVRQMr7FzThAq3ACq_BhphYPcYHm-J5m9u7tVoSy0dD0I9RnHeKUbDLIHnLENItcqBkWVO6wM-Td55m3N_ZlSpY9op7WJerVYhL2zsF7OxSS_B636xVFblaJkjQLub5YWgdZ0plQnsCR6jNGwhsD3qFXT18NYmr1cB6cNWjFMHoY2XQef_RPVZ1k-P3mt_ep5nUx1f5MkV6Wp5ng2G4bci63RDUlsGGg09Ul6QIqZwvcGqE08v8N1YE-Y5kb3mhQm9UCG1-Rnp2BhuNpvXckK1Ir0TKJim7nBMfLGo31PCq7l0zc1zN4RunFQadFy-PWfUqTfJoOn2JjydumVKJGq3E6EWt5zWW1UJDIXKKKut50br7zOittjZ23Gvyz8&modules=).

XMP metadata is similar, but since it's represented as XML, it's much easier to create and parse.

**Comment by brcarp** [comment]
I don't know if this is of any use, but [go-exif-update](https://github.com/sfomuseum/go-exif-update) supports WebAssembly

**Comment by brcarp** [comment]
If you need IPTC in particular, you might need to do some more work. There are good tools out there in various languages (`pyexiv2` in Python, `ExifTool` in Perl [don't laugh, it's actually a great command-line tool). Your best bet would probably be to look at `libiptcdata` since it's written in C, it could potentially be compiled to WebAssembly using tools like Emscripten.

**Comment by kleisauke** [comment]
> I don't know if this is of any use, but [go-exif-update](https://github.com/sfomuseum/go-exif-update) supports WebAssembly

Note that EXIF data is natively supported in wasm-vips through [libexif](https://github.com/libexif/libexif).
https://github.com/kleisauke/wasm-vips/blob/48489c1a7c0f146b52d82592e17e9759413a0829/test/unit/test_foreign.js#L269-L284

However, we're exploring further improvements, as discussed in https://github.com/libvips/libvips/issues/4002.

**Comment by boustanihani** [comment]
Thank you all for the valuable information :)

**Comment by brcarp** [comment]
I've used the source code of ExifTool in the past to directly manipulate the byte data of IPTC metadata blocks, as [kleisauke](https://github.com/kleisauke)'s playground link above demonstrates for the `readIPTCData` function. You could follow that pattern and write a function for `writeIPTCData`, and build yourself a small IPTC-manipulation library.
