### ISSUE TITLE
Accurate progress tracking 

### ISSUE THREAD

**Issue by miloxeon** [kleisauke/wasm-vips#78]
Hi again!

In [this playground demo](https://wasm-vips.kleisauke.nl/playground/?deflate=RZC7asMwFIZfRXixAkXeOqRJhpQWAoWW0k5JBtk-thV0QzqOE0rfvUe2myy2pPP9F2mfVc5GZGXfNBDYmslBKmQNYNXxvEP0cVkURml3AWdF5UwhYwSMhTKyhVgMUmsvPYRYPIqTb_OFwA4sDxA9W29Y-gsZgrxuxwi-WDwdrAZkylDcWfkodslKWBhegzMzNhVK7FTQ9ThNSKSMGIJC-HIznAt5Vk2eaJo5-xFcS8GR2EsqkSycBqFdyy-Lf8tSu5IIymVbWvL9LeP4wH4YXj0sWT7esxj92e-9TxJ_f76Rnr6iCiAR3ssTVEh7nqZ3VpmWuNpVvQGLM_yiIe04BdCjjc1bEUNF5OxNZzdNCzgLttddzXOq6nukx5beg62fO6VrTg7JKHvIVrU6M1WvD9kEHrLNqqCzzTjNjn8), progress tracked using onProgress goes to 100% very quickly, but the lag after that takes way longer, making the tracking near useless. How do I track progress accurately?

**Comment by kleisauke** [comment]
AVIF compression is relatively slow and more memory-intensive compared with most other formats. The performance can also vary depending on the input image, see for example:
https://github.com/libvips/libvips/issues/2983

Additionally, libvips only emits the ["eval" signal](https://www.libvips.org/API/current/VipsImage.html#VipsImage-eval) (on which the [`image.onProgress`](https://github.com/kleisauke/wasm-vips/blob/4702f7df3feeed3efcc07e904de2557a330fce18/lib/vips.d.ts#L518-L531) callback depends) once per work unit during image computation. Since AVIF does not support streaming/chunk-wise encoding, libvips must assemble the entire image in memory before passing it to the AVIF encoder. Consequently, there's no progress feedback during this final compression stage, as libvips considers the computation complete once it reaches this point.

Note that you can control the CPU effort spent on improving AVIF output by passing the `effort` argument:
https://github.com/kleisauke/wasm-vips/blob/4702f7df3feeed3efcc07e904de2557a330fce18/lib/vips.d.ts#L7178-L7181

It defaults to `4`; lowering it to `0` will significantly speed up encoding (but will result in larger file sizes).

**Comment by miloxeon** [comment]
wow, it indeed speeds things up. Didn't know about the AVIF situation. Thanks!
