### ISSUE TITLE
Repeated request `vips-es6.js`

### ISSUE THREAD

**Issue by emojiiii** [kleisauke/wasm-vips#88]
When I use `import Vips from "wasm-vips"` to import, many `vips-es6.js` requests are generated during runtime. When I check the source code, I find the following code `function Pe() { var a = new URL("vips-es6.js", import.meta.url); a = new Worker(a, { type: "module", name: "em-pthread" }); Le.push(a) }`.

`vips-es6.js` is also imported into the worker, which seems to lead to repeated import of `vips-es6.js`. Is there any way to optimize this problem?

<img width="1010" alt="image" src="https://github.com/user-attachments/assets/9392b2a9-a0d5-45d0-a005-889905805d24" />

**Comment by kleisauke** [comment]
This behavior is intentional. Emscripten's pthread integration uses self-referencing web workers, meaning the main document and all workers share the same script. As a result, fewer network requests are made since the main script is cached before any web worker is created.

See commit d6cdcbbb3104b3a3688c3fd71320e88945ab30b1 for more details.

**Comment by emojiiii** [comment]
thanks a lot.
